
* About

  DrupalBox is a template Drupal project that can be used to seed
  (create) a new Drupal project quickly and easily.

  The new project will contain:
  - A Drupal profile (which can also be based on the OpenAtrium
    profile or the Drupal Commons profile).
  - Make files for downloading the Drupal core, all the needed
    modules, libraries, patches, etc.
  - Scripts for installing a minimal Ubuntu server with all the
    packages and configurations needed for running a Drupal
    application.
  - Scripts, modules, tools and docs that facilitate the development,
    including a dev-->test-->live workflow.

  It creates a new project by renaming files of the template project
  and doing find/replace in them.


* Installation

  The recommended way of installation is to build a new server from
  scratch, inside a chroot environment.

  + Get a copy of the template project from GitHub:
    #+BEGIN_EXAMPLE
    mkdir /var/chroot
    cd /var/chroot/
    git clone https://github.com/dashohoxha/dbox.git labdoo
    #+END_EXAMPLE

  + Rename the project:
    #+BEGIN_EXAMPLE
    labdoo/rename-project.sh labdoo:myproject lbd:mpr
    #+END_EXAMPLE

  + Modify and customize the settings:
    #+BEGIN_EXAMPLE
    cp myproject/install/settings.sh myproject/cfg.sh
    vim myproject/cfg.sh
    #+END_EXAMPLE

  + Install the project inside a chroot system:
    #+BEGIN_EXAMPLE
    nohup nice myproject/install/chroot.sh myproject/cfg.sh &
    tail -f nohup.out
    less -r nohup.out
    #+END_EXAMPLE

    This will install in /var/chroot/ a minimal ubuntu system and
    everything that is needed for the normal work of the system. It
    will also make the neccessary common configurations of the system.
    After installation the system should be rebooted.

  + The installation script will also create the init script
    =/etc/init.d/chroot-mpr=, which can be used to start and stop the
    services inside the chroot:
    #+BEGIN_EXAMPLE
    /etc/init.d/chroot-mpr start
    /etc/init.d/chroot-mpr stop
    #+END_EXAMPLE

  + If this is a local copy (installed on a local machine), then add
    the domain name =dev.myproject.org= on ~/etc/hosts~:
    #+BEGIN_EXAMPLE
    127.0.0.1       dev.myproject.org  localhost
    #+END_EXAMPLE
    This way it can be accessed by typing =https://dev.myproject.org=
    on the browser location (not =https://127.0.0.1= or
    =https://localhost=).


* Motivation

  The aim of this project is to be like a "Drupal-on-Rails" for
  helping the new Drupal developers to get started and for simplifying
  the life of the experienced Drupal developers.

  Usually a huge number of skills is needed in order to complete
  successfully a Drupal project, like: server management, web stack
  management, database management, knowledge of drush, Drupal
  profiles, frequently used modules, common Drupal development
  patterns and paradigms, etc. A new Drupal developer cannot possibly
  get all this skills in a short time, so he is not able to finish
  properly a Drupal application or it will take him a very long
  time. This project offers them a Drupal solution that works out of
  the box, with reasonable settings and configurations, which they can
  use as a starting point for developing their application.

  This project can also simplify the life of the experienced Drupal
  developers, by allowing them to get started quickly, and then
  customizing the solution as they wish.


* Documentation

  - Internal doc files:
    + [[https://github.com/dashohoxha/dbox/blob/master/README.org][README.org]] (this file)
    + [[https://github.com/dashohoxha/dbox/blob/master/dev/README.org][dev/README.org]] (tips for developers)
    + [[https://github.com/dashohoxha/dbox/blob/master/modules/features/README.org][modules/features/README.org]]

  - External docs:
    + http://academia.edu/3993827/Development_Setup_Of_B-Translator
    + http://academia.edu/3992404/Using_Drupal_Features_In_B-Translator
    + http://www.academia.edu/4054221/Cloning_a_B-Translator_Server

  - Other docs that may be useful:
    + http://codeinthehole.com/writing/pull-requests-and-other-good-practices-for-teams-using-github/
    + http://dashohoxha.blogspot.com/2012/08/how-to-secure-ubuntu-server.html
    + http://dashohoxha.blogspot.com/2013/07/how-to-manage-your-own-domain-name.html
    + http://dashohoxha.blogspot.com/2013/02/how-to-set-up-chroot-environment-for.html
    + http://dashohoxha.blogspot.com/2012/10/using-nginx-as-web-server-for-drupal.html
    + http://www.havetheknowhow.com/Configure-the-server/Install-ssmtp.html
    + http://arstechnica.com/security/2009/12/how-to-get-set-with-a-secure-sertificate-for-free/
